table Dim_Calendario
	lineageTag: d629ecfa-dd6f-4884-afd2-b7867f77f95d

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 93b2ca41-5777-4fb6-9d7b-a1ce82827a99
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: a4130c32-59e4-4739-b3ea-e2a3fdc80444
			defaultHierarchy: LocalDateTable_c56fa44f-4998-4159-b91d-2a7ad898a126.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: b8e28b57-2b26-4c1c-930e-4c0a6eba9eed
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 44de68b5-c596-4299-918f-1359469ffb65
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 6b1d99c1-9e71-4b17-8b43-4f2867e2556a
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: fffe17bc-4aae-4417-9359-0692c0880823
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: d3e7045c-91e2-4151-8538-c3b0c00dce48
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rodum\Downloads\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Origen{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Tipo cambiado" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

